### ISSUE TITLE
Modernization/Porting tracking issue

### ISSUE THREAD

**Issue by IonAgorria** [KranX/Perimeter#58]
I open this meta-issue to keep track of all issues identified that are required to solve so the game can be ported to modern 64bits Windows and non-Windows OSes.

### Removing incompatible dependencies:
- [X] Embedded Boost removal https://github.com/KranX/Perimeter/issues/42
- [X] Embedded STLport removal https://github.com/KranX/Perimeter/issues/41

### Code/Building:
- [ ] 64 bits support https://github.com/KranX/Perimeter/issues/26
- [ ] Modern compilers support
  - [X] GCC/MinGW
  - [ ] Clang
  - [ ] MSVC https://github.com/KranX/Perimeter/issues/25
- [X] CMake support https://github.com/KranX/Perimeter/issues/13

### Windowing/Input:
- [ ] Replace Win32 Window with SDL2 window
- [ ] Replace input handling with SDL2 input events

### Graphics:
- [ ] Modern API renderer https://github.com/KranX/Perimeter/issues/14
  - [ ] Workaround: reusing existing DirectX renderer with wrapper like DXVK
- [ ] Deprecated dependency on DirectX extensions (d3dx9)

### Music/Sound issues:
- [ ] PlayOgg module depends on Windows API sound https://github.com/KranX/Perimeter/issues/50
- [ ] Game module depends on DirectX's DirectSound API which is Windows only
  - [ ] Make DirectSound code dependency optional
  - [ ] Evaluate SDL2/SDL2-mixer as potential replacement
  - [ ] Remove DirectSound dependency
 
### Network:
- [ ] Game module depends on DirectX's DirectPlay 8 which is deprecated and removed on modern DirectX SDK's, should be replaced with cross-platform compatible lib
  - [ ] Make DirectPlay code dependency optional
  - [ ] Evaluate SDL2-net as potential replacement
  - [ ] Remove DirectPlay dependency
- [ ] Gamespy should be removed https://github.com/KranX/Perimeter/issues/49

### Other issues:
- [ ] Bink video codec and files replacement https://github.com/KranX/Perimeter/issues/48
- [ ] Math code cleanup and modernization https://github.com/KranX/Perimeter/issues/46
- [ ] Code cleanup, line endings, UTF8 https://github.com/KranX/Perimeter/issues/20
